# Especificação para a DigitalOcean App Platform
name: fintelis
region: nyc

services:
- name: fintelis-app
  # Configura o ambiente para PHP
  environment_slug: php
  # Aponta o servidor para a pasta 'public' por segurança
  source_dir: /
  document_root: /public
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  # Conecta ao repositório do GitHub
  github:
    repo: lleonardo-franco/fintelis
    branch: main
    deploy_on_push: true
  # Mapeia as variáveis de ambiente do banco de dados para a aplicação
  envs:
  - key: DB_HOST
    scope: RUN_TIME
    value: ${db.HOSTNAME}
  - key: DB_PORT
    scope: RUN_TIME
    value: ${db.PORT}
  - key: DB_NAME
    scope: RUN_TIME
    value: ${db.DB_NAME}
  - key: DB_USER
    scope: RUN_TIME
    value: ${db.USERNAME}
  - key: DB_PASS
    scope: RUN_TIME
    value: ${db.PASSWORD}


databases:
- name: db
  engine: MYSQL
  version: "8"
  production: true # Pode ser alterado para 'true' para um banco de produção